<?php

use Drupal\multisite_helper_content\Hook\EntityBaseFieldInfo;

/**
 * @file
 * Adds install- and update hooks for the multisite_helper_content module.
 */

/**
 * Installs the sync fields to the node entity type.
 */
function multisite_helper_content_install(): void {
  $fields = EntityBaseFieldInfo::getSyncFields();

  $entity_definition_update_manager = \Drupal::entityDefinitionUpdateManager();
  foreach ($fields as $field_name => $field_definition) {
    $entity_definition_update_manager->installFieldStorageDefinition(
      $field_name,
      'node',
      'node',
      $field_definition,
    );
  }
}
